### ISSUE TITLE
SwiftUI-style encapsulation

### ISSUE THREAD

**Issue by wilg** [Alja7dali/swift-web-page#1]
Being able to encapsulate things like SwiftUI's `View` would be very helpful.

Slightly confusing to get it working, but we have been trying a solution like this (for Vapor):

```swift
import Swep
import Vapor

extension HTMLView {
    func encodeResponse(for request: Request) async throws -> Response {
        var headers = HTTPHeaders()
        headers.add(name: .contentType, value: "text/html; charset=utf-8")
        let view = Layout(app: request.application, content: self)
        return .init(
            headers: headers,
            body: .init(string: view.render())
        )
    }
}

typealias HTMLContent = HtmlNode & ChildOfAny

protocol HTMLView: HtmlNode, AsyncResponseEncodable {
    associatedtype Content: HTMLContent
    @HtmlNodeBuilder var body: Content { get }
}

extension HTMLView {
    func render<T>(_ mode: RenderMode, into target: inout T) where T: TextOutputStream {
        body.render(mode, into: &target)
    }
}

struct SimpleHTMLView<Content: HTMLContent>: HTMLView {
    internal init(@HtmlNodeBuilder content: @escaping () -> Content) {
        self.content = content
    }

    let content: () -> Content
    var body: some HTMLContent {
        content()
    }
}
```

**Comment by Alja7dali** [comment]
Hi @wilg, encapsulating unrelated html tags will mix the parent-child order of html hierarchy, thus sometimes it gives a nonsense compile-time error. However, what you have mentioned is really good point. In near future, I'll push an update to ease the encapsulation part similar to what you did but I need to test it with other tags as well.

**Comment by Alja7dali** [comment]
Hi @wilg, I just released a new library that complement [Swep](https://github.com/Alja7dali/swift-web-page) handles the encapsulation for now! check it out [SwepUI](https://github.com/Alja7dali/swift-web-page-ui) and can't wait to hear your feedback..

**Comment by wilg** [comment]
Very cool! I'll check it out!
